### ISSUE TITLE
Release orocos_toolchain 2.7.0

### ISSUE THREAD

**Issue by meyerj** [orocos-toolchain/orocos_toolchain#5]
This thread collects all issues in orocos_toolchain that probably should be solved before releasing orocos_toolchain 2.7:
- [x] Make orocos_toolchain a metapackage (orocos-toolchain#3)
- [x] Catkin env-hooks in orocos_toolchain (orocos-toolchain#4, orocos-toolchain#6)
- [x] orocos_typegen_headers() broken (orocos-toolchain/rtt#13)
- [x] Add os::CleanupFunction to clear the GlobalService (orocos-toolchain/rtt#15)
- [x] orocreate-pkg: provide package.xml file (jhu-lcsr-forks/ocl#1)
- [x] add `UNBUFFERED` ConnPolicy type constant (orocos-toolchain/rtt_ros_integration#3)

Please add issues here or reference this issue if you have something to add...
